### ISSUE TITLE
Question: Can this work on Windows 10?

### ISSUE THREAD

**Issue by dagalufh** [ehoppmann/abc_dl#1]
Hi,

Do you know if this can work on Windows 10?
If so, what more than Python3 and ffmpeg might be needed?

Thanks in advance.

**Comment by ehoppmann** [comment]
I haven't tested it, but I think I generally wrote everything in a portable manner. If it doesn't work, it would probably only require a very small modification to get it working. All you should need are python3, the requests package for python3, and ffmpeg (in your PATH, so you can call ffmpeg from the command line without specify the full path to it). If it doesn't work let me know where things go wrong so we can get this working.
